authors:
  Juma Shafara:
    name: Juma Shafara
    description: Data Scientist at Raising The Village, Instructor at DATAIDEA
    avatar: https://i.pravatar.cc/150?img=1
  Data Science Team:
    name: Data Science Team
    description: AI & Data Science Enthusiast
    avatar: https://i.pravatar.cc/150?img=3
