authors:
  Your Name:
    name: Your Name
    description: Blog Author
    avatar: https://i.pravatar.cc/150?img=1
  Data Science Team:
    name: Data Science Team
    description: AI & Data Science Enthusiast
    avatar: https://i.pravatar.cc/150?img=3
