authors:
  Juma Shafara:
    name: Juma Shafara
    description: Data Scientist at Raising The Village, Instructor at DATAIDEA
    avatar: https://github.com/jumashafara.png
  DATAIDEA Team:
    name: DATAIDEA Team
    description: Programming for Data Science
    avatar: https://github.com/dataideaorg.png
